stages:
  - test

variables:
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"

default:
  image: rust:slim
  cache:
    key:
      files:
        - Cargo.lock
      prefix: cargo-cloud
    paths:
      - .cargo/bin/
      - .cargo/registry/
      - target/
  before_script:
    - rustc --version
    - cargo --version

.test-base:
  stage: test
  rules:
    # 1. run for MRs to main, BUT ONLY if Rust files changed
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      changes:
        - "**/*.rs"
        - "Cargo.toml"
        - "Cargo.lock"
    # 2. run for commits to main, BUT ONLY if Rust files changed
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - "**/*.rs"
        - "Cargo.toml"
        - "Cargo.lock"
  script:
    - cargo test --workspace

test:x86_64:
  extends: .test-base
  tags:
    - saas-linux-small-amd64

test:aarch64:
  extends: .test-base
  tags:
    - saas-linux-small-arm64