stages:
  - test

variables:
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"

default:
  image: rust:slim
  cache:
    key:
      files:
        - Cargo.lock
      prefix: cargo-cloud
    paths:
      - .cargo/bin/
      - .cargo/registry/
      - target/
  before_script:
    - rustc --version
    - cargo --version

test:x86_64:
  stage: test
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - cargo test --workspace

test:aarch64:
  stage: test
  tags:
    - saas-linux-small-arm64
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - cargo test --workspace