[package]
name = "nyx"
version = "0.6.0"
edition = "2024"

[[bin]]
name = "nyx"
path = "src/main.rs"
bench = false

[workspace]
members = ["backend", "frontend", "fmt", "lsp", "macros"]
resolver = "2"

[dependencies]
clap = { version = "4", features = ["derive"] }
backend = { path = "./backend" }
fmt = { path = "./fmt" }

[dev-dependencies]
criterion = "0.5"
libloading = "0.8"
backend = { path = "./backend" }
frontend = { path = "./frontend" }
bumpalo = "3"

[[bench]]
name = "basic"
harness = false

[[bench]]
name = "stages"
harness = false

[profile.bench]
opt-level = 3
codegen-units = 1
lto = false
debug = false
